volumes:
  postgres_data:
  redis_data:

networks:
  default:

services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "mydatabase", "-U", "user"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.4.2-bookworm
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  projects-api:
    build: .
    container_name: projects-api
    restart: always
    environment:
      BINDING_ADDRESS: "0.0.0.0"
      BINDING_PORT: 3000
      POSTGRES_URL: postgresql://user:password@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
